### PR TITLE
CI repair

### PR DESCRIPTION
**Pull request by jpgrayson**
- update testing certs (#156)
- update to `actions/checkout@v4` (resolves GitHub deprecation warning)
- add Swift 6.0 to test matrix

N.B. there remains a GitHub deprecation warning related to `codecov/codecov-action@v2`, which uses an out of date version of node. But to migrate to `codecov/codecov-action@v4` requires setting up a codecov token [as described here](https://docs.codecov.com/docs/adding-the-codecov-token), which requires a repo admin permissions.

### CODE REVIEW

**Comment by adam-fowler** [comment]
I'm wondering if a better solution is to generate new certs in the GitHub action so they never expire for CI.

**Comment by adam-fowler** [comment]
Also codecov wasn't even enabled on this repo, when it got moved to swift-server-community. You might as well up the version number on the action and I'll see if I can fix it

**Comment by jpgrayson** [comment]
Added the change for codecov. You'll need to define a `CODECOV_TOKEN` secret as shown here:

https://docs.codecov.com/docs/adding-the-codecov-token

**Comment by jpgrayson** [comment]
> I'm wondering if a better solution is to generate new certs in the GitHub action so they never expire for CI.

That's an idea. Given the trouble I had with needing to use MacOS' libreSSL versus homebrew's OpenSSL, it might be that the `generate-certs.sh` script needs some tweaks to be more compatible with the different openssl implementations out there.

**Comment by jpgrayson** [comment]
bump @adam-fowler 

I think this PR is ready to go. The updated codecov seems to be working. The CI failure is due to codecov detecting -0.96% less coverage, but the process itself seems to be working.

I was not planning on trying to do the CI-time cert generation in this PR.

**Review by adam-fowler — APPROVED** [review]

**Comment by adam-fowler** [comment]
Done. Thanks for this @jpgrayson

**Pull request merged**
