### PR TITLE
Update swiftformat

### PR DESCRIPTION
**Pull request by jpgrayson**
This updates the validation tooling to use `swiftformat` 0.52.10 (was 0.48.17).

I'm assuming there is value in updating tooling from time to time. If not, we can just close this PR.

This updated version of `swiftformat` does drive several formatting changes. The most common is to change, e.g.:

```swift
if let thing = thing {
    ...
}
```

to

```swift
if let thing {
    ...
```

which seems like a nice enough improvement.

### CODE REVIEW

**Comment by adam-fowler** [comment]
Is `if let thing` available in swift 5.7? I thought it came in 5.9. 
MQTTNIO supports the last three minor releases of Swift which include 5.7

**Comment by jpgrayson** [comment]
Since `swiftformat` is configured for a particular minimum swift version, I was sort of trusting it to do the right thing in this regard.

The[ CI build/test with swift 5.7](https://github.com/swift-server-community/mqtt-nio/actions/runs/7019818778/job/19098139658?pr=151) also works. 

So it seems like this is okay.

**Comment by adam-fowler** [comment]
Of course you're right. Thanks for all the changes.

**Review by adam-fowler — APPROVED** [review]

**Comment by jpgrayson** [comment]
Thank you for taking the time to review these PR's. I very much appreciate your help!

**Pull request merged**
